package com.example.demo.chemicals.repository

import org.springframework.data.jpa.repository.config.EnableJpaRepositories
import org.springframework.transaction.annotation.EnableTransactionManagement

@EnableJpaRepositories
@EnableTransactionManagement
class RepositoryConfiguration
